name = "ProbabilityThing"
uuid = "0d5a40a8-8b64-4e50-8e06-029ea7c81911"
authors = ["Aron <aronpjansen@gmail.com> and contributors"]
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
